### ISSUE TITLE
rc-field-form依赖出错

### ISSUE THREAD

**Issue by luanshi1127** [Pong420/rc-field-form#8]
![Snipaste_2021-02-25_10-02-58](https://user-images.githubusercontent.com/47845440/109091942-ac7e9d00-7750-11eb-9d0b-94b6f1e8d8ad.png)

使用的时dva+antd构建的项目，在下过antd依赖后就会报这个错，请问怎么解决啊？

**Comment by Pong420** [comment]
抱歉，可能repo 的名字讓你誤會了，
rc-field-form的 github 是這個 https://github.com/react-component/field-form
這個repo 只是將rc-fied-form 包裝
